wiki/encyclopedia/urls.py
from django.urls import path, re_path

from . import views
from django.conf.urls import url

app_name="encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:name>", views.title, name='title'),
    path("search", views.search, name="search"),
    path("create", views.create, name="create"),
    path("wiki/edit/<str:name>", views.edit, name="edit"),
    path("randompg", views.randompg, name="randompg")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from . import util
from django.core.files.base import ContentFile
from django.core.files.base import File
from django.urls import reverse
import random
from markdown2 import Markdown

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def title(request, name):
    entryList = util.list_entries()
    if name in entryList:
        page = util.get_entry(name)
        markdowner = Markdown()
        convertedpage = markdowner.convert(page)
        if "h1" in convertedpage:
            return render(request, "encyclopedia/title.html", {
                "wikititle": name,
                "wikidetail": convertedpage
            })
        else:
            return render(request, "encyclopedia/title.html", {
                "wikititle": name,
                "wikidetail": convertedpage,
                "val": "1"
            })
    else:
        return render(request, "encyclopedia/title.html", {
            "wikititle": "404",
            "wikidetail": "Entry does not exist"
        })

def search(request):
    query = request.GET.get('q')
    print(query)

    entryList = util.list_entries()
    allSubstring = [s for s in entryList if query in s]

    if query in entryList:
        page = util.get_entry(query)
        return redirect(f'/wiki/{ query }')
    elif len(allSubstring) > 0:
        allSubstring = [s for s in entryList if query in s]
        return render(request, "encyclopedia/result.html", {
            "subList": allSubstring,
            "val": "2"
        })
    else:
        return render(request, "encyclopedia/result.html", {
            "noEnt": "0 results...",
            "val": "3"
        })

def create(request):
    entryList = util.list_entries()

    title = request.POST.get('title', '')
    content = request.POST.get('content', '')
    if title in entryList:
        if len(title) >= 1:
            return render(request, "encyclopedia/create.html", {
                "errMsg": "ERROR: entry already exists!",
                "val": "1"
            })
        else:
            return render(request, "encyclopedia/create.html", {
                "errMsg": "Enter a title",
                "val": "1"
            })
    elif title == "":
        return render(request, "encyclopedia/create.html")
    else:
        util.save_entry(title, content)
        return redirect(f'wiki/{ title }')

def edit(request, name):
    wikientry = util.get_entry(name)
    entryList = util.list_entries()

    newtitle = request.POST.get('title', '')
    newcontent = request.POST.get('content', '')
    print(newtitle)
    if newtitle == "":
        return render(request, "encyclopedia/edit.html", {
        "orgtitle": name,
        "orgcontent": wikientry,
        "newtitle": newtitle
    })
    else:
        util.save_entry(newtitle, newcontent)
        return HttpResponseRedirect(reverse('encyclopedia:title', args=(name,)))

def randompg(request):
    entryList = util.list_entries()
    totalEntries = 0
    
    for i in entryList:
        totalEntries += 1
    
    entryArr = [totalEntries]

    for i in entryList:
        entryArr.append(i)

    randomNum = random.randint(1, totalEntries)
    chosenPage = entryArr[randomNum]        
    print(chosenPage)
    print(totalEntries)
    print(randomNum)
    if chosenPage!="":
        return redirect(f'wiki/{ chosenPage }')
    else:
        randomNum = random.randint(1, totalEntries)
        chosenPage = entryArr[randomNum]        
        print(chosenPage)
        print(totalEntries)
        print(randomNum)
        return redirect(f'wiki/{ chosenPage }')

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <h1>Create New Wiki</h1>
    
    INFO: You will get redirected if your entry is saved

    <br></br>
    {% if val == "1"%}
        <strong>{{ errMsg }}</strong>
    {% endif %}

    <br></br>

    <form action="{% url 'encyclopedia:create'%}" method="POST">
        {% csrf_token %}        
        <input type="text" name="title">
        <br></br>
        <strong>Enter Content</strong>
        <br></br>
        <textarea class="content" name="content" rows="5" cols="30">
        </textarea>
        <br></br>
        <input type="submit" name="submit">
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Entry
{% endblock %}

{% block body %}
    <h1>Edit Entry:</h1>

    INFO: You will get redirected if your entry is saved
    <br></br>
    
    <form action="{% url 'encyclopedia:edit' orgtitle %}" method="POST">
        {% csrf_token %}        
        <strong>Enter Title:</strong>
        <br></br>
        <input type="text" name="title" value={{ orgtitle }}>
        <br></br>
        <strong>Enter Content:</strong>
        <br></br>
        <textarea class="content" name="content" rows="5" cols="30">
{{ orgcontent }}
        </textarea>
        <br></br>
        <input type="submit" name="submit">
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            {% if entry != ""%}
                <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
            {% endif %}
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:randompg' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/randompg.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    {{wikititle}}
{% endblock %}

{% block body %}
    <h1>{{ wikititle }}</h1> 
    <a href="{% url 'encyclopedia:edit' wikititle %}"><strong>Edit</strong></a>
    <br></br>

    <ul>
        <li>{{wikidetail}}</li>
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/result.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Results
{% endblock %}

{% block body %}

    <h1>Search Results:</h1>
        {% if val == "1" %}
            <a href="/wiki/{{ query }}">{{ query }}</a>
        {% endif %}

        {% if val == "2" %}
            <ul>
                {% for entry in subList %}
                    <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
                {% endfor %}
            </ul>
        {% endif %}

        {% if val == "3"%}
           <h2> {{ noEnt }} </h2>
        {% endif %}

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/title.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
    {{wikititle}}
{% endblock %}

{% block body %}

    {% if val == "1"%}
        <h1>{{ wikititle }}</h1>
    {% endif %}

    {{wikidetail|safe}}
    

    <a href="{% url 'encyclopedia:edit' wikititle %}"><strong>Edit</strong></a>
{% endblock %}